sitemap:
  changefreq: daily
  filename: sitemap.xml
  priority: 0.5


baseURL: "https://armanasq.github.io/" 
title: Arman Asgharpoor Golroudbari
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: pmichaillat

taxonomies:
    tag: tags

menu:
    main:
        - name: CV
          url: /cv/
        - name: Papers
          url: /papers/
          weight: 1
        - name: Robotic
          url: /robotic/
          weight: 2
        - name: Astronomy
          url: /astronomy/
          weight: 3
        - name: Talks
          url: /talks/
          weight: 4
        - name: Teaching
          url: /teaching/
          weight: 5  
        - name: Tags
          url: /tags/
          weight: 6   

params:
    description: "I have recently graduated with an MSc in Space Engineering from the University of Tehran, where I had the privilege of working under the guidance of [Dr. M. H. Sabour](https://scholar.google.com/citations?user=R86XDtUAAAAJ&hl=en). My Master's thesis focused on the utilization of deep learning in state estimation, specifically the Intelligent Filters, for Inertial Attitude Estimation."
    author: Arman Asgharpoor Golroudbari
    googleAnalyticsID: "376058559"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Arman Asgharpoor Golroudbari
          subtitle: "I have recently graduated with an MSc in Space Engineering from the University of Tehran, where I had the privilege of working under the guidance of [Dr. M. H. Sabour](https://scholar.google.com/citations?user=R86XDtUAAAAJ&hl=en). My Master's thesis focused on the utilization of deep learning in state estimation, specifically the Intelligent Filters, for Inertial Attitude Estimation."
          imageUrl: "/bio-photo.jpeg"
          imageWidth: 170
          imageHeight: 170
          imageTitle: Arman Asgharpoor Golroudbari
          buttons:
            - name: Papers
              url: /papers/
            - name: Robotic
              url: /robotic/
            - name: Astronomy
              url: /astronomy/
            - name: Talks
              url: /talks/
            - name: Teaching
              url: /teaching/
            - name: Certificates
              url: /certificates/
  
    socialIcons:
        - name: CV
          url: "/cv.pdf"
        - name: Email
          url: "mailto:a.asgharpoor1993@gmail.com"
        - name: Location
          url: /location/
        - name: Google Scholar
          url: "https://scholar.google.com/citations?hl=en&user=IlAgF9UAAAAJ"
        - name: GitHub
          url: "https://github.com/armanasq"

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Arman Asgharpoor"
      icon: /favicon.png
      iconHeight: 25

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
    extensions:
      - "github.com/mohd-akram/remark-math"



# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
